version: '2'
services:
    db:
        image: mysql:latest
        volumes:
            - "./.data/db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: vivadecora
            MYSQL_DATABASE: vehicles_api
            MYSQL_USER: vivadecora
            MYSQL_PASSWORD: vivadecora
    api:
        build: ./vehiclemanager/
        command: gunicorn -b 0.0.0.0:8000 -w 5 -k gevent --log-file - --log-level debug --access-logfile - vehiclemanager.wsgi
        volumes:
            - ./vehiclemanager/:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    frontend:
        image: nginx
        volumes:
            - ./frontend/:/usr/share/nginx/html/
        ports:
            - "80:80"
        depends_on:
            - api
